package site.leawsic.chess.screen;

import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.player.Inventory;
import org.lwjgl.glfw.GLFW;
import site.leawsic.chess.Chess;
import site.leawsic.chess.block.XiangqiBoardBlockEntity;
import site.leawsic.chess.config.XiangqiConfig;
import site.leawsic.chess.network.ChessNetwork;
import site.leawsic.chess.screen.handler.XiangqiMenu;

public class XiangqiScreen extends AbstractContainerScreen<XiangqiMenu> {
    private int boardLeft,boardTop;private float scale;private int sx=-1,sy=-1;private long escapeAt,noticeUntil;private Component notice;private Button reset,join,leave,red,black,ai;
    public XiangqiScreen(XiangqiMenu menu,Inventory inventory,Component title){super(menu,inventory,title);imageWidth=360;imageHeight=340;}
    public void showNotice(Component n){notice=n;noticeUntil=System.currentTimeMillis()+5000;}
    private XiangqiBoardBlockEntity board(){return menu.board();} private void send(Object p){ChessNetwork.CHANNEL.sendToServer(p);} private void simple(java.util.function.Function<net.minecraft.core.BlockPos,Object> f){if(board()!=null)send(f.apply(board().getBlockPos()));}
    @Override protected void init(){super.init();imageWidth=Math.min(width-32,544);imageHeight=Math.min(height-32,580);leftPos=(width-imageWidth)/2;topPos=(height-imageHeight)/2;scale=Math.min((imageWidth-16)/(float)XiangqiConfig.BOARD_TEXTURE_SIZE,(imageHeight-72)/(float)XiangqiConfig.BOARD_TEXTURE_SIZE);boardLeft=leftPos+(imageWidth-Math.round(XiangqiConfig.BOARD_TEXTURE_SIZE*scale))/2;boardTop=topPos+24;reset=btn("gui.chess.clear",leftPos+10,topPos+imageHeight-24,60,b->simple(ChessNetwork.XiangqiResetPacket::new));join=btn("gui.chess.join",leftPos+75,topPos+imageHeight-24,55,b->simple(ChessNetwork.JoinGamePacket::new));leave=btn("gui.chess.leave",leftPos+135,topPos+imageHeight-24,55,b->simple(ChessNetwork.LeaveGamePacket::new));red=btn("gui.chess.xq.host_red",leftPos+imageWidth-190,topPos+imageHeight-24,85,b->colors(1,-1));black=btn("gui.chess.xq.host_black",leftPos+imageWidth-100,topPos+imageHeight-24,85,b->colors(-1,1));ai=btn("gui.chess.xq.ai",leftPos+10,topPos+imageHeight-48,80,b->simple(ChessNetwork.ToggleAiPacket::new));}
    private Button btn(String k,int x,int y,int w,java.util.function.Consumer<Button>a){Button b=Button.builder(Component.translatable(k),a::accept).bounds(x,y,w,20).build();addRenderableWidget(b);return b;}private void colors(int h,int g){if(board()!=null)send(new ChessNetwork.SetPieceTypesPacket(board().getBlockPos(),h,g));}
    @Override protected void renderBg(GuiGraphics g,float d,int mx,int my){ResourceLocation tex=new ResourceLocation(Chess.MODID,"textures/"+XiangqiConfig.BOARD_TEXTURE.getPath()+".png");int boardPixels=Math.round(XiangqiConfig.BOARD_TEXTURE_SIZE*scale);g.blit(tex,boardLeft,boardTop,boardPixels,boardPixels,0,0,512,512,512,512);XiangqiBoardBlockEntity b=board();if(b==null)return;for(int y=0;y<10;y++)for(int x=0;x<9;x++){int p=b.getBoard()[y][x];if(p==0)continue;ResourceLocation pt=new ResourceLocation(Chess.MODID,"textures/"+XiangqiConfig.pieceTexture(p).getPath()+".png");int cX=Math.round(boardLeft+scale*(XiangqiConfig.textureX(x)-20)),cY=Math.round(boardTop+scale*(XiangqiConfig.textureY(y)-20)),s=Math.round(40*scale);g.blit(pt,cX,cY,s,s,0,0,40,40,40,40);if(x==sx&&y==sy)g.renderOutline(cX-1,cY-1,s+2,s+2,0xFFFFFF00);}int[] m={b.getLastFromX(),b.getLastFromY(),b.getLastToX(),b.getLastToY()};for(int i=0;i<4;i+=2)if(XiangqiConfig.inBounds(m[i],m[i+1])){int cx=Math.round(boardLeft+scale*XiangqiConfig.textureX(m[i])),cy=Math.round(boardTop+scale*XiangqiConfig.textureY(m[i]));g.renderOutline(cx-23,cy-23,46,46,0xFFFFD54F);}}
    @Override protected void renderLabels(GuiGraphics g,int mx,int my){XiangqiBoardBlockEntity b=board();if(b==null)return;updateButtons(b);Component status=b.isGameOver()?Component.translatable(b.getWinner()==1?"gui.chess.xq.red_wins":"gui.chess.xq.black_wins"):b.isAiThinking()?Component.translatable("gui.chess.xq.ai_turn"):Component.translatable(b.getCurrentPlayer()==1?"gui.chess.xq.red_turn":"gui.chess.xq.black_turn");g.drawString(font,status,10,10,0xFFFFFFFF,false);if(b.isGameOver())ChessScreenUi.gameOver(g,font,imageWidth,imageHeight,status);if(!b.isGameOver()&&XiangqiConfig.isInCheck(b.getBoard(),b.getCurrentPlayer()))g.drawCenteredString(font,Component.translatable(b.getCurrentPlayer()==1?"gui.chess.xq.red_in_check":"gui.chess.xq.black_in_check"),imageWidth/2,25,0xFFFFD54F);}
    private void updateButtons(XiangqiBoardBlockEntity b){boolean host=minecraft.player!=null&&b.isHost(minecraft.player.getUUID()),player=minecraft.player!=null&&b.isInGame(minecraft.player.getUUID()),turn=player&&b.getPlayerPieceType(minecraft.player.getUUID())==b.getCurrentPlayer();reset.active=host&&!b.isGameOver();join.active=!player&&b.getGuestPlayer()==null;leave.active=player;red.active=host&&!b.isGameStarted();black.active=host&&!b.isGameStarted();ai.active=host&&!b.isGameOver()&&!b.isMultiplayer();}
    @Override public boolean mouseClicked(double mx,double my,int button){XiangqiBoardBlockEntity b=board();int col=Math.round((float)((mx-boardLeft)/scale-XiangqiConfig.BOARD_LEFT_U)/XiangqiConfig.CELL_PIXELS),row=Math.round((float)((my-boardTop)/scale-XiangqiConfig.BOARD_TOP_V)/XiangqiConfig.CELL_PIXELS);boolean turn=minecraft.player!=null&&b!=null&&b.isInGame(minecraft.player.getUUID())&&b.getPlayerPieceType(minecraft.player.getUUID())==b.getCurrentPlayer()&&!b.isGameOver()&&!b.isAiThinking();if(turn&&XiangqiConfig.inBounds(col,row)){if(sx<0){if(b.getBoard()[row][col]!=0&&XiangqiConfig.color(b.getBoard()[row][col])==b.getPlayerPieceType(minecraft.player.getUUID())){sx=col;sy=row;}}else{send(new ChessNetwork.XiangqiMovePacket(b.getBlockPos(),sx,sy,col,row));sx=sy=-1;}return true;}return super.mouseClicked(mx,my,button);}
    @Override public boolean keyPressed(int key,int scan,int mods){if(key!=GLFW.GLFW_KEY_ESCAPE)return super.keyPressed(key,scan,mods);long now=System.currentTimeMillis();if(now-escapeAt>1500){escapeAt=now;showNotice(Component.translatable("gui.chess.exit_confirm"));return true;}simple(ChessNetwork.LeaveGamePacket::new);onClose();return true;}@Override public boolean shouldCloseOnEsc(){return false;}
    @Override public void render(GuiGraphics g,int mx,int my,float delta){renderBackground(g);super.render(g,mx,my,delta);if(notice!=null&&noticeUntil>System.currentTimeMillis())g.drawCenteredString(font,notice,width/2,height/2,0xFFFFFFFF);}
}
