package site.leawsic.chess.config;

import net.minecraft.resources.ResourceLocation;
import site.leawsic.chess.block.BaseBoardBlockEntity;
import java.util.List;
import java.util.function.BiFunction;

public class ChessGameConfig {
    private final int rows, cols, playerCount, initialPlayer, boardTextureWidth, boardTextureHeight, boardLeftU, boardTopV, pieceTextureSize, pieceDrawSize;
    private final float boardCellPixelSize, pieceOffsetX, pieceOffsetY;
    private final List<PieceType> pieceTypes; private final ResourceLocation[] pieceTextures;
    private final ResourceLocation boardTopTexture, boardBottomTexture, boardSideTexture;
    private final String translationKey; private final List<int[]> starPoints;
    private final BiFunction<BaseBoardBlockEntity, Move, PlaceResult> placeRule;
    private final BiFunction<BaseBoardBlockEntity, Integer, PlaceResult> passRule;
    private ChessGameConfig(Builder b) { rows=b.rows; cols=b.cols; playerCount=b.playerCount; initialPlayer=b.initialPlayer; pieceTypes=List.of(b.pieceTypes); pieceTextures=b.pieceTextures.clone(); boardTopTexture=b.boardTopTexture; boardBottomTexture=b.boardBottomTexture; boardSideTexture=b.boardSideTexture; translationKey=b.translationKey; starPoints=b.starPoints == null ? List.of() : List.copyOf(b.starPoints); placeRule=b.placeRule; passRule=b.passRule; boardTextureWidth=b.boardTextureWidth; boardTextureHeight=b.boardTextureHeight; boardLeftU=b.boardLeftU; boardTopV=b.boardTopV; boardCellPixelSize=b.boardCellPixelSize; pieceTextureSize=b.pieceTextureSize; pieceDrawSize=b.pieceDrawSize; pieceOffsetX=b.pieceOffsetX; pieceOffsetY=b.pieceOffsetY; }
    public int getRows(){return rows;} public int getCols(){return cols;} public int getPlayerCount(){return playerCount;} public int getInitialPlayer(){return initialPlayer;} public int getEmptyValue(){return 0;} public PieceType getPieceType(int id){return pieceTypes.get(id);} public ResourceLocation getPieceTexture(int id){return pieceTextures[id];} public ResourceLocation getBoardTopTexture(){return boardTopTexture;} public ResourceLocation getBoardBottomTexture(){return boardBottomTexture;} public ResourceLocation getBoardSideTexture(){return boardSideTexture;} public String getTranslationKey(){return translationKey;} public List<int[]> getStarPoints(){return starPoints;} public int getBoardTextureWidth(){return boardTextureWidth;} public int getBoardTextureHeight(){return boardTextureHeight;} public int getBoardLeftU(){return boardLeftU;} public int getBoardTopV(){return boardTopV;} public float getBoardCellPixelSize(){return boardCellPixelSize;} public int getPieceTextureSize(){return pieceTextureSize;} public int getPieceDrawSize(){return pieceDrawSize;} public float getPieceCenterU(int col){return boardLeftU+col*boardCellPixelSize+pieceOffsetX;} public float getPieceCenterV(int row){return boardTopV+row*boardCellPixelSize+pieceOffsetY;}
    public PlaceResult checkPlacement(BaseBoardBlockEntity e, Move m){return placeRule.apply(e,m);} public boolean supportsPass(){return passRule!=null;} public PlaceResult checkPass(BaseBoardBlockEntity e,int p){return passRule==null?PlaceResult.fail():passRule.apply(e,p);}
    public record PieceType(int id,String name){public static final PieceType EMPTY=new PieceType(0,"empty");}
    public record PlaceResult(boolean success,boolean switchPlayer,boolean gameOver,int winner,List<Move> capturedPieces,int koX,int koY,double blackScore,double whiteScore){public static PlaceResult success(boolean s){return success(s,List.of(),-1,-1);} public static PlaceResult success(boolean s,List<Move> c,int x,int y){return new PlaceResult(true,s,false,-1,List.copyOf(c),x,y,0,0);} public static PlaceResult gameOver(int w){return gameOver(w,0,0);} public static PlaceResult gameOver(int w,double b,double wh){return new PlaceResult(true,false,true,w,List.of(),-1,-1,b,wh);} public static PlaceResult fail(){return new PlaceResult(false,false,false,-1,List.of(),-1,-1,0,0);}}
    public static class Builder { private int rows=15,cols=15,playerCount=2,initialPlayer=1,boardTextureWidth=256,boardTextureHeight=256,boardLeftU=19,boardTopV=19,pieceTextureSize=32,pieceDrawSize=12; private float boardCellPixelSize=12,pieceOffsetX,pieceOffsetY; private PieceType[] pieceTypes={PieceType.EMPTY,new PieceType(1,"black"),new PieceType(2,"white")}; private ResourceLocation[] pieceTextures; private ResourceLocation boardTopTexture,boardBottomTexture,boardSideTexture; private String translationKey="board.generic"; private List<int[]> starPoints=List.of(); private BiFunction<BaseBoardBlockEntity,Move,PlaceResult> placeRule; private BiFunction<BaseBoardBlockEntity,Integer,PlaceResult> passRule;
        public Builder rows(int v){rows=v;return this;} public Builder cols(int v){cols=v;return this;} public Builder playerCount(int v){playerCount=v;return this;} public Builder initialPlayer(int v){initialPlayer=v;return this;} public Builder pieceTypes(PieceType...v){pieceTypes=v;return this;} public Builder pieceTextures(ResourceLocation...v){pieceTextures=v;return this;} public Builder boardTopTexture(ResourceLocation v){boardTopTexture=v;return this;} public Builder boardBottomTexture(ResourceLocation v){boardBottomTexture=v;return this;} public Builder boardSideTexture(ResourceLocation v){boardSideTexture=v;return this;} public Builder translationKey(String v){translationKey=v;return this;} public Builder starPoints(List<int[]>v){starPoints=v;return this;} public Builder placeRule(BiFunction<BaseBoardBlockEntity,Move,PlaceResult>v){placeRule=v;return this;} public Builder passRule(BiFunction<BaseBoardBlockEntity,Integer,PlaceResult>v){passRule=v;return this;} public Builder boardTextureWidth(int v){boardTextureWidth=v;return this;} public Builder boardTextureHeight(int v){boardTextureHeight=v;return this;} public Builder boardLeftU(int v){boardLeftU=v;return this;} public Builder boardTopV(int v){boardTopV=v;return this;} public Builder boardCellPixelSize(float v){boardCellPixelSize=v;return this;} public Builder pieceTextureSize(int v){pieceTextureSize=v;return this;} public Builder pieceDrawSize(int v){pieceDrawSize=v;return this;} public Builder pieceOffset(float x,float y){pieceOffsetX=x;pieceOffsetY=y;return this;} public ChessGameConfig build(){if(pieceTextures==null||boardTopTexture==null||boardBottomTexture==null||boardSideTexture==null||placeRule==null)throw new IllegalStateException("Missing required textures or rule");return new ChessGameConfig(this);}}
}
