package site.leawsic.chess.config;

import net.minecraft.resources.ResourceLocation;
import site.leawsic.chess.Chess;
import site.leawsic.chess.block.BaseBoardBlockEntity;
import java.util.*;

public final class GomokuConfig {
    public static final ChessGameConfig CONFIG=baseConfig().translationKey("block.chess.gomoku_board").placeRule(GomokuConfig::placeGomokuPiece).build();
    public static final ChessGameConfig GO_CONFIG=baseConfig().translationKey("block.chess.go_board").placeRule(GomokuConfig::placeGoPiece).passRule(GomokuConfig::passGoTurn).build();
    private GomokuConfig(){}
    private static ChessGameConfig.Builder baseConfig(){return new ChessGameConfig.Builder().rows(19).cols(19).playerCount(2).initialPlayer(1).pieceTypes(ChessGameConfig.PieceType.EMPTY,new ChessGameConfig.PieceType(1,"black"),new ChessGameConfig.PieceType(2,"white")).pieceTextures(null,Chess.id("block/piece_black"),Chess.id("block/piece_white")).boardTopTexture(Chess.id("block/gomoku_board_top")).boardBottomTexture(Chess.id("block/go_board_bottom")).boardSideTexture(new ResourceLocation("minecraft","block/birch_planks")).starPoints(List.of(new int[]{3,3},new int[]{3,9},new int[]{3,15},new int[]{9,3},new int[]{9,9},new int[]{9,15},new int[]{15,3},new int[]{15,9},new int[]{15,15})).boardTextureWidth(256).boardTextureHeight(256).boardLeftU(19).boardTopV(19).boardCellPixelSize(12.125f).pieceTextureSize(14).pieceDrawSize(11).pieceOffset(0,0);}
    private static ChessGameConfig.PlaceResult placeGomokuPiece(BaseBoardBlockEntity e,Move m){int[][] b=e.getBoard();int x=m.x(),y=m.y(),p=m.player(),cols=e.getConfig().getCols(),rows=e.getConfig().getRows();for(int[] d:new int[][]{{1,0},{0,1},{1,1},{1,-1}}){int count=1;for(int i=1;i<5;i++){int nx=x+d[0]*i,ny=y+d[1]*i;if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&b[ny][nx]==p)count++;else break;}for(int i=1;i<5;i++){int nx=x-d[0]*i,ny=y-d[1]*i;if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&b[ny][nx]==p)count++;else break;}if(count>=5)return ChessGameConfig.PlaceResult.gameOver(p);}return ChessGameConfig.PlaceResult.success(true);}
    private static ChessGameConfig.PlaceResult placeGoPiece(BaseBoardBlockEntity e,Move m){int[][] b=e.getBoard();int x=m.x(),y=m.y(),p=m.player(),op=p==1?2:1,cols=e.getConfig().getCols(),rows=e.getConfig().getRows();if(b[y][x]!=0||e.getKoX()==x&&e.getKoY()==y)return ChessGameConfig.PlaceResult.fail();int[][] test=copyBoard(b,rows,cols);test[y][x]=p;Set<Long> captured=new HashSet<>();for(int[]d:DIRS){int nx=x+d[0],ny=y+d[1];if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&test[ny][nx]==op){Set<Long> group=new HashSet<>();if(!hasLiberty(nx,ny,op,test,cols,rows,group))captured.addAll(group);}}for(long pos:captured)test[(int)pos][(int)(pos>>32)]=0;Set<Long> self=new HashSet<>();if(!hasLiberty(x,y,p,test,cols,rows,self))return ChessGameConfig.PlaceResult.fail();List<Move> moves=new ArrayList<>();for(long pos:captured)moves.add(new Move((int)(pos>>32),(int)pos,op));int koX=-1,koY=-1;if(captured.size()==1&&self.size()==1){long pos=captured.iterator().next();koX=(int)(pos>>32);koY=(int)pos;}return ChessGameConfig.PlaceResult.success(true,moves,koX,koY);}
    private static ChessGameConfig.PlaceResult passGoTurn(BaseBoardBlockEntity e,int p){if(e.getConsecutivePasses()<1)return ChessGameConfig.PlaceResult.success(true);Score s=calculateScore(e.getBoard(),e.getConfig().getRows(),e.getConfig().getCols());int w=s.blackScore()>s.whiteScore()?1:s.whiteScore()>s.blackScore()?2:0;return ChessGameConfig.PlaceResult.gameOver(w,s.blackScore(),s.whiteScore());}
    private static final int[][] DIRS={{1,0},{-1,0},{0,1},{0,-1}};
    private static boolean hasLiberty(int x,int y,int p,int[][]b,int cols,int rows,Set<Long>g){long key=((long)x<<32)|(y&0xffffffffL);if(!g.add(key))return false;for(int[]d:DIRS){int nx=x+d[0],ny=y+d[1];if(nx<0||nx>=cols||ny<0||ny>=rows)continue;if(b[ny][nx]==0||b[ny][nx]==p&&hasLiberty(nx,ny,p,b,cols,rows,g))return true;}return false;}
    private static int[][] copyBoard(int[][]b,int rows,int cols){int[][]c=new int[rows][cols];for(int r=0;r<rows;r++)System.arraycopy(b[r],0,c[r],0,cols);return c;}
    public static Score calculateScore(int[][]b,int rows,int cols){boolean[][]v=new boolean[rows][cols];double black=0,white=6.5;for(int y=0;y<rows;y++)for(int x=0;x<cols;x++){if(b[y][x]==1)black++;else if(b[y][x]==2)white++;else if(!v[y][x]){Territory t=collectTerritory(x,y,b,v,rows,cols);if(t.borderColor()==1)black+=t.size();else if(t.borderColor()==2)white+=t.size();}}return new Score(black,white);}
    private static Territory collectTerritory(int sx,int sy,int[][]b,boolean[][]v,int rows,int cols){Deque<Long>q=new ArrayDeque<>();q.add(((long)sx<<32)|(sy&0xffffffffL));v[sy][sx]=true;int size=0,border=0;boolean mixed=false;while(!q.isEmpty()){long c=q.removeFirst();int x=(int)(c>>32),y=(int)c;size++;for(int[]d:DIRS){int nx=x+d[0],ny=y+d[1];if(nx<0||nx>=cols||ny<0||ny>=rows)continue;int value=b[ny][nx];if(value==0&&!v[ny][nx]){v[ny][nx]=true;q.add(((long)nx<<32)|(ny&0xffffffffL));}else if(value!=0){if(border==0)border=value;else if(border!=value)mixed=true;}}}return new Territory(size,mixed?0:border);}
    public record Score(double blackScore,double whiteScore){} private record Territory(int size,int borderColor){}
}
